backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "頁面"
    files:
      - label: "服務概覽"
        name: "serviceOverviews"
        file: "content/serviceOverviews.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "服務"
            name: "services"
            widget: list
            fields:
              - { label: "服務名稱", name: "serviceName", widget: "string" }
              - { label: "預覽相片", name: "thumbnail", widget: "image" }
              - { label: "價格至", name: "priceTo", widget: "number", required: false }
              - { label: "價格由", name: "priceFrom", widget: "number", required: false }
              - { label: "服務詳情", name: "serviceDescription", widget: "text", required: false }
      - label: "關於金星"
        name: "aboutus"
        file: "content/aboutus.md"
        fields:
          - { label: "公司簡介", name: "companyIntro", widget: "markdown" }
          - { label: "創辦人介紹", name: "founderIntro", widget: "markdown" }
          - label: "媒體報導"
            name: "mediaReports"
            widget: "list"
            fields:
              - { label: "標題", name: "header", widget: "string", required: false }
              - { label: "預覽相片", name: "thumbnail", widget: "image" }
              - { label: "Link", name: "link", widget: "string" }
          - label: "使命與願景"
            name: "missions"
            widget: "list"
            fields:
              - { label: "標題", name: "header", widget: "string" }
              - { label: "內容", name: "description", widget: "text" }
          - { label: "服務承諾", name: "ourPromises", widget: "list" }
      - label: "特色服務"
        name: "specialServices"
        file: "content/specialServices.md"
        fields:
          - label: "服務"
            name: "services"
            widget: list
            fields:
              - { label: "服務名稱", name: "serviceName", widget: "string" }
              - { label: "預覽相片", name: "thumbnail", widget: "image", required: false }
              - { label: "價格至", name: "priceTo", widget: "number", required: false }
              - { label: "價格由", name: "priceFrom", widget: "number", required: false }
              - { label: "服務詳情", name: "serviceDescription", widget: "text", required: false }
      - label: "帛事花牌"
        name: "flowerService"
        file: "content/flowerService.md"
        fields:
          - { label: "描述", name: "description", widget: "text" }
          - { label: "服務重點", name: "serviceKeyPoints", widget: "list" }
          - label: "花牌相片"
            name: "services"
            widget: list
            fields:
              - { label: "花牌名稱", name: "flowerName", widget: "string" }
              - { label: "相片", name: "thumbnail", widget: "image" }
              - { label: "等級", name: "tier", widget: "select", options: ["A", "B", "C", "D", "E", "F"] }
      - label: "服務流程"
        name: "processes"
        file: "content/processes.md"
        fields:
          - { label: "流程", name: "processes", widget: "list" }
      - label: "聯絡我們"
        name: "processes"
        file: "content/processes.md"
        fields:
          - { label: "描述", name: "description", widget: "text" }
          - { label: "地址", name: "address", widget: "string" }
          - { label: "Google Map Url", name: "googleMapUrl", widget: "string", required: false }
          - { label: "電郵地址", name: "phoneNumber", widget: "string", required: false }
          - { label: "電郵地址", name: "email", widget: "string", required: false }
          - { label: "Facebook Link", name: "facebookLink", widget: "string", required: false }
          - { label: "Instagram Link", name: "instagramLink", widget: "string", required: false }      
      - label: "客戶見證"
        name: "testimonies"
        file: "content/testimonies.md"
        fields:
          - { label: "客戶名稱", name: "name", widget: "string" }
          - { label: "內容", name: "content", widget: "text" }
          - { label: "日期", name: "createdDate", widget: "date", required: false }
  # - name: "testimonies"
  #   label: "客戶見證"
  #   folder: "testimonies/"
  #   create: true
  #   files:
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Body", name: "body", widget: "markdown"}